package Interfaz;

import Clases.Control_Ingresos;
import Clases.Personas;
import Controlador.Funciones;
import Tabla.Render;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Fernando Rhenals
 */
public class frmRegistro extends javax.swing.JDialog {

    Control_Ingresos control = new Control_Ingresos();
    Personas pers = new Personas();
    private final Timer timer = new Timer();
    Calendar c2 = new GregorianCalendar();
    private TableRowSorter trsfiltro;
    String filtro;
    String idPersona;

    /**
     * Creates new form frmRegistro
     */
    public frmRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = jTextField1.getText();
                jTextField1.setText(cadena);
                repaint();
                filtro();
            }
        });

        jDFecha.setCalendar(c2);
        this.setLocationRelativeTo(null);

        timer.schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Limpiar();
            }
        }, 10, 30000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jApellido = new javax.swing.JLabel();
        jFechaIngreso = new javax.swing.JLabel();
        jHoraIngreso = new javax.swing.JLabel();
        jHoraSalida = new javax.swing.JLabel();
        jEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLFoto = new javax.swing.JLabel();
        jDFecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jcbOpcion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(716, 507));
        setMinimumSize(new java.awt.Dimension(716, 507));
        setSize(new java.awt.Dimension(716, 507));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 49, 50));

        jPanel1.setBackground(new java.awt.Color(51, 49, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Ingreso:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora Ingreso:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora Salida:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado:");

        jId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jId.setForeground(new java.awt.Color(255, 255, 255));
        jId.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jNombre.setForeground(new java.awt.Color(255, 255, 255));
        jNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jApellido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jApellido.setForeground(new java.awt.Color(255, 255, 255));
        jApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jFechaIngreso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jFechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jFechaIngreso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jHoraIngreso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jHoraIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jHoraIngreso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jHoraSalida.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jHoraSalida.setForeground(new java.awt.Color(255, 255, 255));
        jHoraSalida.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jEstado.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jEstado.setForeground(new java.awt.Color(255, 255, 255));
        jEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jHoraIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(jNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(51, 49, 50));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTable1.setBackground(new java.awt.Color(51, 49, 50));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTROS ENTRADA/SALIDA");

        jLFoto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLFoto.setForeground(new java.awt.Color(255, 255, 255));
        jLFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jDFecha.setBackground(new java.awt.Color(204, 204, 204));
        jDFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jDFecha.setPreferredSize(new java.awt.Dimension(4, 23));
        jDFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDFechaFocusGained(evt);
            }
        });
        jDFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDFechaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDFechaMousePressed(evt);
            }
        });
        jDFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDFechaKeyPressed(evt);
            }
        });
        jDFecha.getDateEditor().addPropertyChangeListener(new PropertyChangeListener(){
            public void propertyChange(PropertyChangeEvent e) {
                if (jDFecha.getDate() != null){
                    LlenarlistaPorFecha();
                }
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 49, 50));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jcbOpcion.setBackground(new java.awt.Color(51, 49, 50));
        jcbOpcion.setEditable(true);
        jcbOpcion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jcbOpcion.setForeground(new java.awt.Color(255, 255, 255));
        jcbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nombre", "Apellido", "Fecha Ingreso", "Hora Ingreso", "Hora Salida", "Estado" }));
        jcbOpcion.setSelectedIndex(1);
        jcbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(jcbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(262, 262, 262)))
                                .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            RESET();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Se detecto una ejecución indebida. El programa se cerrará", "ERROR", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        if (evt.getClickCount() == 2) {

            if (jTable1.getSelectedColumn() != -1) {
                jId.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                jNombre.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                jApellido.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
                jFechaIngreso.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
                jHoraIngreso.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
                jHoraSalida.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 5));
                jEstado.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 6));

                //Activo = 1;
                /*0  Funciones.PasarGrilla(evt, jTable1, botonGuardar, botonModificar, botonEliminar, Activo);*/
            }
            ObtenerFoto();
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        if (evt.getClickCount()==2){
//            
//        
//        if (jTable1.getSelectedColumn() != -1) {
//            jId.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
//            jNombre.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
//            jApellido.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
//          //  jFoto.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
//            jFechaIngreso.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
//            jHoraIngreso.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 5));
//            jHoraSalida.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 6));
//            jEstado.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 7));
//
//            //Activo = 1;
//          /*0  Funciones.PasarGrilla(evt, jTable1, botonGuardar, botonModificar, botonEliminar, Activo);*/
//        }
//        }// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseExited

    private void jDFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDFechaKeyPressed

    }//GEN-LAST:event_jDFechaKeyPressed

    private void jDFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDFechaMousePressed
        //LlenarlistaPorFecha();
    }//GEN-LAST:event_jDFechaMousePressed

    private void jDFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDFechaMouseClicked
        // LlenarlistaPorFecha();        // TODO add your handling code here:
    }//GEN-LAST:event_jDFechaMouseClicked

    private void jDFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDFechaFocusGained
        LlenarlistaPorFecha();        // TODO add your handling code here:
    }//GEN-LAST:event_jDFechaFocusGained

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

        if (jcbOpcion.getSelectedItem().toString() == "Estado") {
            jTextField1.setText(jTextField1.getText().toUpperCase());
            trsfiltro = new TableRowSorter(jTable1.getModel());
            jTable1.setRowSorter(trsfiltro);
        } else {
            if (jTextField1.getText().length() > 0) {
                Funciones.PasarTextAPrimeraMayuscula(evt, jTextField1);
                trsfiltro = new TableRowSorter(jTable1.getModel());
                jTable1.setRowSorter(trsfiltro);
            }

        }


    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased


    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jcbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jcbOpcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmRegistro dialog = new frmRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellido;
    private com.toedter.calendar.JDateChooser jDFecha;
    private javax.swing.JLabel jEstado;
    private javax.swing.JLabel jFechaIngreso;
    private javax.swing.JLabel jHoraIngreso;
    private javax.swing.JLabel jHoraSalida;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcbOpcion;
    // End of variables declaration//GEN-END:variables

    private void LlenarlistaPorFecha() {

        Date fecha = jDFecha.getDate();
        DateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        String fecha2 = f.format(fecha);
       

        jTable1.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dt.addColumn("Id");
        dt.addColumn("Nombre");
        dt.addColumn("Apellido");
        dt.addColumn("Fecha Ingreso");
        dt.addColumn("Hora Ingreso");
        dt.addColumn("Hora Salida");
        dt.addColumn("Estado");
        //String Cabecera[] = {"Id", "Nombre", "Apellido", "Foto", "Fecha Ingreso", "Hora Ingreso", "Hora Salida", "Estado"};
        try {

            control.setFecha_ingreso(fecha2);
            LinkedList<Control_Ingresos> list = control.ListarIngresoPorFecha(frmSplash.con);
            Iterator ilist = list.iterator();
            Object fila[] = new String[7];
            while (ilist.hasNext()) {

                Control_Ingresos cont = (Control_Ingresos) ilist.next();

                fila[0] = String.valueOf(cont.getIdIngreso());
                fila[1] = cont.getNombre();
                fila[2] = cont.getApellido();
                fila[3] = cont.getFecha_ingreso();
                fila[4] = cont.getHora_ingreso();
                fila[5] = cont.getHora_salida();

                if (cont.getEstado() == 1) {
                    fila[6] = "ENTRADA";
                } else {
                    fila[6] = "SALIDA";
                }

                dt.addRow(fila);
            }
            jTable1.setModel(dt);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    private void ObtenerFoto() {
        pers.setIdPersonas(jId.getText());
        try {
            pers.BuscarPersonaPorFoto(frmSplash.con);
            try {
                byte[] bi = pers.getFoto();
                BufferedImage image = null;
                InputStream in = new ByteArrayInputStream(bi);
                image = ImageIO.read(in);
                ImageIcon imgi = new ImageIcon(image.getScaledInstance(182, 240, 0));
                jLFoto.setIcon(imgi);
            } catch (Exception ex) {
                jLFoto.setText("No imagen");

            }

        } catch (SQLException ex) {
            Logger.getLogger(frmRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ObtenerID() {

        try {
            control.setIdPersonas(jId.getText());
            control.ObtenerIdPersona(frmSplash.con);
            idPersona = control.getIdPersonas();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    private void Llenarlista() {

        jTable1.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dt.addColumn("Id");
        dt.addColumn("Nombre");
        dt.addColumn("Apellido");
        dt.addColumn("Foto");
        dt.addColumn("Fecha Ingreso");
        dt.addColumn("Hora Ingreso");
        dt.addColumn("Hora Salida");
        dt.addColumn("Estado");
        //String Cabecera[] = {"Id", "Nombre", "Apellido", "Foto", "Fecha Ingreso", "Hora Ingreso", "Hora Salida", "Estado"};
        try {

            LinkedList<Control_Ingresos> list = control.ListarIngreso(frmSplash.con);
            Iterator ilist = list.iterator();
            Object fila[] = new String[8];
            while (ilist.hasNext()) {

                Control_Ingresos cont = (Control_Ingresos) ilist.next();

                fila[0] = String.valueOf(cont.getIdIngreso());
                fila[1] = cont.getNombre();
                fila[2] = cont.getApellido();

//                try {
//                    byte[] bi = cont.getFoto();
//                    BufferedImage image = null;
//                    InputStream in = new ByteArrayInputStream(bi);
//                    image = ImageIO.read(in);
//                    ImageIcon imgi = new ImageIcon(image.getScaledInstance(60, 60, 0));
//                    fila[3] = new JLabel(imgi);
//                } catch (Exception ex) {
//                    fila[3] = "No imagen";
//                }
                fila[4] = cont.getFecha_ingreso();
                fila[5] = cont.getHora_ingreso();
                fila[6] = cont.getHora_salida();

                if (cont.getEstado() == 1) {
                    fila[7] = "ENTRADA";
                } else {
                    fila[7] = "SALIDA";
                }

                dt.addRow(fila);
            }
            jTable1.setModel(dt);
            jTable1.setRowHeight(60);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        try {
            control.ListarIngresoPorFecha(frmSplash.con);

            //ValidarDatosTabla();
        } catch (SQLException ex) {
            Logger.getLogger(frmRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ValidarDatosTabla() {
        if (jTable1.getRowCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(80);
        } else {
            JOptionPane.showMessageDialog(null, "No data to display");
            this.dispose();
        }

    }

    public void RESET() {
        LlenarlistaPorFecha();
    }

    public void filtro() {
        String opcion = jcbOpcion.getSelectedItem().toString();

        if (opcion == "Id") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 0));
        }
        if (opcion == "Nombre") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 1));
        }
        if (opcion == "Apellido") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 2));
        }
        if (opcion == "Fecha Ingreso") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 3));
        }
        if (opcion == "Hora Ingreso") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 4));
        }
        if (opcion == "Hora Salida") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 5));
        }
        if (opcion == "Estado") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 6));
        }

    }

    public void Limpiar() {
        timer.cancel();
        jId.setText("");
        jNombre.setText("");
        jApellido.setText("");
        jEstado.setText("");
        jFechaIngreso.setText("");
        jHoraIngreso.setText("");
        jHoraSalida.setText("");
        jDFecha.setCalendar(c2);
        jLFoto.setIcon(null);
    }

}
