/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Personas;
import Controlador.Funciones;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Fernando Rhenals
 */
public class RegistroPersonas extends javax.swing.JInternalFrame {

    Personas pers = new Personas();
    String idCed;
    private TableRowSorter trsfiltro;
    String filtro;

    /**
     * Creates new form RegistroPersonas
     */
    public RegistroPersonas() {
        initComponents();
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = jTextField1.getText();
                jTextField1.setText(cadena);
                repaint();
                filtro();
            }
        });

    }

    private void Llenarlista() {

        String Cabecera[] = {"Id Personas", "Nombre", "Apellido", "Direccion", "Telefono", "Email", "Rol", "Fecha Nacimiento", "Id NFC", "Numero Ficha"};
        DefaultTableModel dtm = new DefaultTableModel(null, Cabecera);
        jTable1.setModel(dtm);
        try {
            LinkedList<Personas> list = pers.ListarPersonas(frmSplash.con);
            Iterator ilist = list.iterator();
            String fila[] = new String[10];
            while (ilist.hasNext()) {
                Personas pers = (Personas) ilist.next();
                fila[0] = pers.getIdPersonas();
                fila[1] = pers.getNombre();
                fila[2] = pers.getApellido();
                fila[3] = pers.getDireccion();
                fila[4] = pers.getTelefono();
                fila[5] = pers.getEmail();
                switch (pers.getRol_idrol()) {
                    case 1:
                        fila[6] = "ADMINISTRADOR";
                        break;
                    case 2:
                        fila[6] = "VIGILANTE";
                        break;
                    case 3:
                        fila[6] = "INSTRUCTOR";
                        break;

                    case 4:
                        fila[6] = "APRENDIZ";
                        break;
                    case 5:
                        fila[6] = "VISITANTE";
                        break;
                }
                fila[7] = pers.getFecha_nacimiento();
                fila[8] = String.valueOf(pers.getNFC_id());
                fila[9] = pers.getNumero_ficha();

                dtm = (DefaultTableModel) jTable1.getModel();
                dtm.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        ValidarDatosTabla();

    }

    public void ValidarDatosTabla() {
        if (jTable1.getRowCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(160);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(120);
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros");
            //this.dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jcbOpcion = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 49, 50));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 49, 50));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRO DE PERSONAS");

        btnEliminar.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/32x32/if_Cancel__Red_34208.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/32x32/if_xfce-system-exit_23651.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 49, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jcbOpcion.setBackground(new java.awt.Color(51, 49, 50));
        jcbOpcion.setEditable(true);
        jcbOpcion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jcbOpcion.setForeground(new java.awt.Color(255, 255, 255));
        jcbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Personas", "Nombre", "Apellido", "Direccion", "Telefono", "Email", "Rol", "Fecha Nacimiento", "Id NFC", "Numero Ficha" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(jcbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        if (jTable1.getSelectedColumn() != -1) {
            idCed = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        }

    }//GEN-LAST:event_jTable1MousePressed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        RESET();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        pers.setIdPersonas(idCed);
        int opcion = JOptionPane.showConfirmDialog(null, "¿Esta seguro de borrar el registro: " + idCed + "?", "MENSAJE DEL SISTEMA", JOptionPane.YES_NO_OPTION);
        if (opcion == 0) {
            try {
                pers.EliminarPersonas(frmSplash.con);
                JOptionPane.showMessageDialog(null, "REGISTRO BORRADO");
                RESET();
            } catch (SQLException ex) {
                System.err.println(ex.getMessage());
            }
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
//        CerrarSocket();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

        if (jcbOpcion.getSelectedItem().toString() != "Rol" && jcbOpcion.getSelectedItem().toString() != "Email") {
            if (jTextField1.getText().length() > 0) {
                Funciones.PasarTextAPrimeraMayuscula(evt, jTextField1);
            }

            trsfiltro = new TableRowSorter(jTable1.getModel());
            jTable1.setRowSorter(trsfiltro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcbOpcion;
    // End of variables declaration//GEN-END:variables

    public void RESET() {
        idCed = "";
        Llenarlista();
    }

    public void filtro() {
        String opcion = jcbOpcion.getSelectedItem().toString();

        if (opcion == "Id Personas") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 0));
        }
        if (opcion == "Nombre") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 1));
        }
        if (opcion == "Apellido") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 2));
        }
        if (opcion == "Direccion") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 3));
        }
        if (opcion == "Telefono") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 4));
        }
        if (opcion == "Email") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 5));
        }
        if (opcion == "Rol") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 6));
        }
        if (opcion == "Fecha Nacimiento") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 7));
        }
        if (opcion == "Id NFC") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 8));
        }
        if (opcion == "Numero Ficha") {
            filtro = jTextField1.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 9));
        }

    }
}
